"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import store from "../app/store";
import Navigation from '@/Components/Navigation'
import Footer from '@/Components/Footer'

// import {st}
import { Provider } from 'react-redux';
// import Provider from "../Features/Provider"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
      <body className={inter.className}>
      <Provider store={store}>
        <Navigation/>
        {children}
        <Footer/>
        </Provider>
        </body>
      
    </html>
    
  )
}
